services:
  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    restart: unless-stopped
    command: -H tcp://socket-proxy:2375
    volumes:
      - $SERVERDIR/appdata/portainer/data:/data
    networks:
      - t3_proxy
      - socket_proxy
    environment:
      - TZ=$TZ
    labels:
      # Enable Traefik
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.portainer-rtr.entrypoints=websecure"
      - "traefik.http.routers.portainer.rule=Host(`portainer.$DOMAINNAME_HS`) || Host(`portainer.karlhanger.com`)"
      # Middlewares
      - "traefik.http.routers.portainer-rtr.middlewares=chain-no-auth@file"
      # HTTP Services
      - "traefik.http.routers.portainer-rtr.service=portainer-svc"
      - "traefik.http.services.portainer-svc.loadbalancer.server.port=9000"