services:
  cloudflaretunnel:
    container_name: cloudflare-tunnel
    image: cloudflare/cloudflared:latest
    networks:
      - socket_proxy
      - t3_proxy
    restart: always
    env_file: .env
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run

networks:
  t3_proxy:
    external: true
  socket_proxy:
    external: true